site_name: WhiteTreeBible
site_url: https://whitetreebible.com
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Tools:
    - Connections: https://connections.whitetreebible.com
    - Blog: https://blog.whitetreebible.com/blog
  - About:
    - About Us: about/about-us.md
    - Get Updates: about/get-email-updates.md
    - Support Us: about/support-us.md

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "WhiteTreeBible"

markdown_extensions:
  - footnotes   # needed for footnotes to render
  - attr_list   # needed for _target links to render