site_name: WhiteTreeBible
site_url: https://whitetreebible.com
use_directory_urls: true
theme:
  name: mkdocs
plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "WhiteTreeBible"